// Command go-ml-gen compiles a go-ml/v1 model export into Go source, so the
// model is linked statically into your binary with no runtime file or parsing.
//
// Given an export produced by tools/sklexport, it emits a .go file that builds
// the model from literal data and exposes it as a package-level variable:
//
//	go-ml-gen -pkg models -var Model -o models/model_gen.go model.json
//
// Then in your program:
//
//	proba, err := models.Model.PredictProba(X)
//
// Multiple exports can be generated into the same package; pass several inputs
// and an output directory:
//
//	go-ml-gen -pkg models -o models/ iris.json forest.json
//
// The variable name then defaults to the CamelCase of each file's base name.
// Generated files carry a "DO NOT EDIT" banner and are gofmt-clean.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"

	"github.com/heru-public/go-ml/internal/jsonx"
)

func main() {
	pkg := flag.String("pkg", "models", "package name for generated files")
	varName := flag.String("var", "", "exported variable name (single input only; default: CamelCase of file base)")
	out := flag.String("o", "", "output file (single input) or directory (multiple inputs); default: <input>_gen.go")
	flag.Parse()

	inputs := flag.Args()
	if len(inputs) == 0 {
		fmt.Fprintln(os.Stderr, "go-ml-gen: no input exports given")
		flag.Usage()
		os.Exit(2)
	}
	if *varName != "" && len(inputs) != 1 {
		fmt.Fprintln(os.Stderr, "go-ml-gen: -var may only be used with a single input")
		os.Exit(2)
	}

	for _, in := range inputs {
		name := *varName
		if name == "" {
			name = exportVarName(in)
		}
		outPath := outputPath(*out, in, len(inputs))
		if err := generate(in, outPath, *pkg, name); err != nil {
			fmt.Fprintf(os.Stderr, "go-ml-gen: %s: %v\n", in, err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "go-ml-gen: wrote %s (var %s.%s)\n", outPath, *pkg, name)
	}
}

func outputPath(out, in string, n int) string {
	base := strings.TrimSuffix(filepath.Base(in), filepath.Ext(in))
	if out == "" {
		return filepath.Join(filepath.Dir(in), base+"_gen.go")
	}
	if n > 1 || isDir(out) {
		return filepath.Join(out, base+"_gen.go")
	}
	return out
}

func isDir(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && fi.IsDir()
}

// --- go-ml/v1 schema (a local copy; the tool deliberately does not import the
// model packages so it can be built and run without them). ---

type envelope struct {
	Format string          `json:"format"`
	Type   string          `json:"type"`
	Model  json.RawMessage `json:"model"`
}

type treeJSON struct {
	NodeCount   int          `json:"node_count"`
	ValueWidth  int          `json:"value_width"`
	Left        []int32      `json:"left"`
	Right       []int32      `json:"right"`
	Feature     []int32      `json:"feature"`
	Threshold   jsonx.Floats `json:"threshold"`
	MissingLeft []bool       `json:"missing_left"`
	Value       jsonx.Floats `json:"value"`
}

type forestJSON struct {
	NFeatures int          `json:"n_features"`
	NOutputs  int          `json:"n_outputs"`
	Classes   jsonx.Floats `json:"classes"`
	Trees     []treeJSON   `json:"trees"`
}

func generate(in, outPath, pkg, varName string) error {
	data, err := os.ReadFile(in)
	if err != nil {
		return err
	}
	var env envelope
	if err := json.Unmarshal(data, &env); err != nil {
		return fmt.Errorf("parsing envelope: %w", err)
	}
	if env.Format != "go-ml/v1" {
		return fmt.Errorf("unsupported format %q", env.Format)
	}

	var body bytes.Buffer
	usesMath := false
	switch env.Type {
	case "RandomForestClassifier", "ExtraTreesClassifier":
		var f forestJSON
		if err := json.Unmarshal(env.Model, &f); err != nil {
			return fmt.Errorf("parsing model: %w", err)
		}
		usesMath = emitForest(&body, varName, env.Type, &f)
	default:
		return fmt.Errorf("unsupported model type %q", env.Type)
	}

	var src bytes.Buffer
	fmt.Fprintf(&src, "// Code generated by go-ml-gen from %s; DO NOT EDIT.\n\n", filepath.Base(in))
	fmt.Fprintf(&src, "package %s\n\n", pkg)
	src.WriteString("import (\n")
	if usesMath {
		src.WriteString("\t\"math\"\n\n")
	}
	src.WriteString("\t\"github.com/heru-public/go-ml/ensemble\"\n")
	src.WriteString("\t\"github.com/heru-public/go-ml/tree\"\n")
	src.WriteString(")\n\n")
	src.Write(body.Bytes())

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		// Emit unformatted source to aid debugging, then fail.
		_ = os.WriteFile(outPath, src.Bytes(), 0o644)
		return fmt.Errorf("formatting generated source: %w", err)
	}
	if dir := filepath.Dir(outPath); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	return os.WriteFile(outPath, formatted, 0o644)
}

// emitForest writes the var + builder for a tree ensemble of the given
// estimator type and reports whether it referenced the math package (for
// non-finite literals). The scikit-learn estimator name is also the name of the
// Go type and of its constructor's suffix, so it is used verbatim.
func emitForest(w *bytes.Buffer, varName, typeName string, f *forestJSON) bool {
	var fw floatWriter
	fmt.Fprintf(w, "// %s is the statically compiled %s\n", varName, typeName)
	fmt.Fprintf(w, "// (%d trees, %d features, %d classes).\n", len(f.Trees), f.NFeatures, len(f.Classes))
	fmt.Fprintf(w, "var %s = build%s()\n\n", varName, varName)
	fmt.Fprintf(w, "func build%s() *ensemble.%s {\n", varName, typeName)

	fmt.Fprintf(w, "\ttrees := []*tree.Tree{\n")
	for i := range f.Trees {
		t := &f.Trees[i]
		w.WriteString("\t\t{")
		writeInt32Slice(w, "Left", t.Left)
		writeInt32Slice(w, "Right", t.Right)
		writeInt32Slice(w, "Feature", t.Feature)
		w.WriteString("Threshold: []float64{")
		fw.writeFloats(w, t.Threshold)
		w.WriteString("}, ")
		writeBoolSlice(w, "MissingLeft", t.MissingLeft)
		w.WriteString("Value: []float64{")
		fw.writeFloats(w, t.Value)
		w.WriteString("}, ")
		fmt.Fprintf(w, "ValueWidth: %d},\n", t.ValueWidth)
	}
	w.WriteString("\t}\n")

	w.WriteString("\tclasses := []float64{")
	fw.writeFloats(w, f.Classes)
	w.WriteString("}\n")
	fmt.Fprintf(w, "\tm, err := ensemble.New%s(%d, classes, trees)\n", typeName, f.NFeatures)
	w.WriteString("\tif err != nil {\n\t\tpanic(\"go-ml-gen: \" + err.Error())\n\t}\n")
	w.WriteString("\treturn m\n}\n")
	return fw.usedMath
}

func writeInt32Slice(w *bytes.Buffer, name string, xs []int32) {
	fmt.Fprintf(w, "%s: []int32{", name)
	for i, x := range xs {
		if i > 0 {
			w.WriteByte(',')
		}
		w.WriteString(strconv.FormatInt(int64(x), 10))
	}
	w.WriteString("}, ")
}

func writeBoolSlice(w *bytes.Buffer, name string, xs []bool) {
	fmt.Fprintf(w, "%s: []bool{", name)
	for i, x := range xs {
		if i > 0 {
			w.WriteByte(',')
		}
		if x {
			w.WriteString("true")
		} else {
			w.WriteString("false")
		}
	}
	w.WriteString("}, ")
}

// floatWriter formats float64 literals that round-trip exactly, emitting
// math.Inf/math.NaN for non-finite values and recording that math was used.
type floatWriter struct{ usedMath bool }

func (fw *floatWriter) writeFloats(w *bytes.Buffer, xs []float64) {
	for i, x := range xs {
		if i > 0 {
			w.WriteByte(',')
		}
		w.WriteString(fw.format(x))
	}
}

func (fw *floatWriter) format(x float64) string {
	switch {
	case math.IsInf(x, 1):
		fw.usedMath = true
		return "math.Inf(1)"
	case math.IsInf(x, -1):
		fw.usedMath = true
		return "math.Inf(-1)"
	case math.IsNaN(x):
		fw.usedMath = true
		return "math.NaN()"
	default:
		// Shortest representation that parses back to the identical float64.
		return strconv.FormatFloat(x, 'g', -1, 64)
	}
}

// exportVarName turns a file base name into an exported Go identifier, e.g.
// "forest_bench.json" -> "ForestBench".
func exportVarName(path string) string {
	base := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
	var b strings.Builder
	upper := true
	for _, r := range base {
		switch {
		case r == '_' || r == '-' || r == '.' || r == ' ':
			upper = true
		case upper:
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		default:
			b.WriteRune(r)
		}
	}
	name := b.String()
	if name == "" || !unicode.IsLetter(rune(name[0])) {
		name = "Model" + name
	}
	return name
}
